### ISSUE TITLE
Merge/Close button

### ISSUE THREAD

**Issue by kegsay** [Kegsay/github-pull-review#5]
We needs one precious.

**Comment by illicitonion** [comment]
Merge should also have a squash option.

**Comment by illicitonion** [comment]
Also, I will probably do this in the near future, because I want a merge+squash button.

**Comment by kegsay** [comment]
We need a Close button for bad PRs. Then I can close this issue.

**Comment by kegsay** [comment]
YAY WE HAVE ONE!
