### ISSUE TITLE
File moves look weird in diffs page

### ISSUE THREAD

**Issue by illicitonion** [Kegsay/github-pull-review#58]
https://review.rocks/#/repos/matrix-org/matrix-doc/185/diffs?_k=tog8fx

"api/client-server/v2_alpha/account-data.yaml â†’ api/client-server/account-data.yaml"

That â†’ is quite strange

**Comment by kegsay** [comment]
WFM on github.io - agreed it looks wrong on review.rocks - your char encodings must be wrong.
